plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.0'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'net.selev'
version = '0.0.1'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(23)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.slf4j:slf4j-api:2.0.12'
    implementation 'ch.qos.logback:logback-classic:1.5.18'
    implementation 'ch.qos.logback:logback-core:1.5.18'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    implementation platform ('com.konghq:unirest-java-bom:4.4.5')
    implementation 'com.konghq:unirest-java-core'
    implementation 'com.konghq:unirest-modules-gson'
    implementation 'com.google.code.gson:gson:2.13.1'
}

tasks.named('test') {
    useJUnitPlatform()
}
